apiVersion: batch/v1
kind: CronJob
metadata:
  name: artefact-enumerator
spec:
  schedule: {{ default "*/5 * * * *" .Values.schedule | quote }} # schedule may contain asterisks, quote to avoid yaml parser errors
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ default 1 .Values.successful_jobs_history_limit }}
  failedJobsHistoryLimit: {{ default 1 .Values.failed_jobs_history_limit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: artefact-enumerator
        spec:
          containers:
          - name: artefact-enumerator
            image: {{ include "image" .Values.image }}
            imagePullPolicy: IfNotPresent
            command:
            - python3
            - -m
            - artefact_enumerator
            env:
            - name: SECRET_FACTORY_PATH
              value: /secrets
            - name: SCAN_CFG_PATH
              value: /scan_cfg/scan_cfg
            - name: FINDINGS_CFG_PATH
              value: /findings_cfg/findings_cfg
            - name: FEATURES_CFG_PATH
              value: /features_cfg/features_cfg
            - name: K8S_TARGET_NAMESPACE
              value: {{ .Release.Namespace }}
            volumeMounts:
            - name: github
              mountPath: /secrets/github
            - name: kubernetes
              mountPath: /secrets/kubernetes
            - name: oci-registry
              mountPath: /secrets/oci-registry
            - name: scan-cfg
              mountPath: /scan_cfg
            - name: findings-cfg
              mountPath: /findings_cfg
            - name: cfg-factory
              mountPath: "/cfg_factory"
              readOnly: true
            - name: features-cfg
              mountPath: "/features_cfg"
              readOnly: true
            resources:
              requests:
                memory: 150Mi
                cpu: 500m
              limits:
                memory: 300Mi
                cpu: 1000m
          volumes:
            - name: github
              secret:
                secretName: secret-factory-github
                optional: true # TODO: only optional until cfg factory support has been removed
            - name: kubernetes
              secret:
                secretName: secret-factory-kubernetes
                optional: true # might use incluster config
            - name: oci-registry
              secret:
                secretName: secret-factory-oci-registry
                optional: true # TODO: only optional until cfg factory support has been removed
            - name: scan-cfg
              configMap:
                name: scan-cfg
                optional: true # TODO: only optional until old scan cfg has been removed
            - name: findings-cfg
              configMap:
                name: findings-cfg
                optional: true # TODO: only optional until old scan cfg has been removed
            - name: cfg-factory
              secret:
                secretName: cfg-factory-secret
                optional: true
            - name: features-cfg
              secret:
                secretName: features-cfg
                optional: true
          restartPolicy: Never
