apiVersion: apps/v1
kind: Deployment
metadata:
  name: backlog-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backlog-controller
  template:
    metadata:
      labels:
        app: backlog-controller
    spec:
      containers:
        - name: backlog-controller
          image: {{ include "image" (index .Values "backlog-controller" "image") }} # indexing required since `-` is not allowed in variable names
          imagePullPolicy: IfNotPresent
          command:
          - python3
          - -m
          - backlog_controller
          env:
          - name: SECRET_FACTORY_PATH
            value: /secrets
          - name: SCAN_CFG_PATH
            value: /scan_cfg/scan_cfg
          - name: K8S_TARGET_NAMESPACE
            value: {{ .Release.Namespace }}
          volumeMounts:
          - name: kubernetes
            mountPath: /secrets/kubernetes
          - name: scan-cfg
            mountPath: /scan_cfg
          resources:
            requests:
              memory: 100Mi
              cpu: 30m
            limits:
              memory: 300Mi
              cpu: 300m
      volumes:
        - name: kubernetes
          secret:
            secretName: secret-factory-kubernetes
            optional: true # might use incluster config
        - name: scan-cfg
          configMap:
            name: scan-cfg
            optional: true # TODO: only optional until old scan cfg has been removed
